const pets = [
  {
    id: 1,
    name: 'Grim',
    breed: 'Cutest Short Hair Cat',
    age: 2,
    sex: 'f',
    color: 'Black',
    weight: 10,
    parentId: 1,
  },
  {
    id: 2,
    name: 'Davros',
    breed: 'Cat??',
    age: 10,
    sex: 'm',
    color: 'Tuxedo',
    weight: 15,
    parentId: 2,
  },
  {
    id: 3,
    name: 'Hershey',
    breed: 'Labradoodle',
    age: 13,
    sex: 'm',
    color: 'Brown',
    weight: 35,
    parentId: 3,
  },
  {
    id: 4,
    name: 'Koda',
    breed: 'Husky',
    age: 3,
    sex: 'm',
    color: 'black and white',
    weight: 30,
    parentId: 9,
  },
  {
    id: 5,
    name: 'Muggsy',
    breed: 'Pitbull',
    age: 3,
    sex: 'm',
    color: 'Black',
    weight: 80,
    parentId: 11,
  },
  {
    id: 6,
    name: 'Nala',
    breed: 'Yellow Lab',
    age: 3,
    sex: 'f',
    color: 'Blonde',
    weight: 70,
    parentId: 4,
  },
  {
    id: 7,
    name: 'Taco',
    breed: 'Chiweenie',
    age: 6,
    sex: 'm',
    color: 'black',
    weight: 10,
    parentId: 16,
  },
  {
    id: 8,
    name: 'Kyle',
    breed: 'Mink Cat',
    age: 2,
    sex: 'm',
    color: 'Orange',
    weight: 8,
    parentId: 14,
  },
  {
    id: 9,
    name: 'Simon',
    breed: 'Pitbull/Border Collie',
    age: 3,
    sex: 'm',
    color: 'Black and White',
    weight: 35,
    parentId: 8,
  },
  {
    id: 10,
    name: 'Luna',
    breed: 'German Shepherd/Husky',
    age: 1,
    sex: 'f',
    color: 'Black',
    weight: 60,
    parentId: 5,
  },
  {
    id: 11,
    name: 'Hoolee',
    breed: 'Meow (Tabby)',
    age: 6,
    sex: '',
    color: 'Grey',
    weight: 10,
    parentId: 10,
  },
  {
    id: 12,
    name: 'Charlee',
    breed: 'Pit Bull',
    age: 6,
    sex: 'f',
    color: 'Grey',
    weight: 40,
    parentId: 12,
  },
  {
    id: 13,
    name: 'Maverick',
    breed: 'Australian Doodle',
    age: 2,
    sex: 'm',
    color: 'White',
    weight: 40,
    parentId: 5,
  },
  {
    id: 14,
    name: 'Snookums',
    breed: 'bordercollie/terrier',
    age: 7,
    sex: 'f',
    color: 'Blonde',
    weight: 20,
    parentId: 13,
  },
  {
    id: 15,
    name: 'Prince',
    breed: 'German Shepherd',
    age: 2,
    sex: 'm',
    color: 'Brown',
    weight: 70,
    parentId: 7,
  },
  {
    id: 16,
    name: 'Turtle',
    breed: 'Tort cat',
    age: 4,
    sex: 'f',
    color: 'tri color',
    weight: 8,
    parentId: 14,
  },
  {
    id: 17,
    name: 'Winston',
    breed: 'Short hair',
    age: 7,
    sex: 'm',
    color: 'Grey',
    weight: 15,
    parentId: 6,
  },
  {
    id: 18,
    name: 'Twixie',
    breed: 'Guinea Pig',
    age: 5,
    sex: 'f',
    color: 'brown and white',
    weight: 5,
    parentId: 9,
  },
  {
    id: 19,
    name: 'Ladybird',
    breed: 'Mutt?',
    age: 13,
    sex: 'f',
    color: 'orange',
    weight: 30,
    parentId: 15,
  },
  {
    id: 20,
    name: 'Maggie',
    breed: 'Australian Doodle',
    age: 2,
    sex: 'f',
    color: 'White and brown',
    weight: 50,
    parentId: 5,
  },
  {
    id: 21,
    name: 'Adonis',
    breed: 'Pitty Mix',
    age: 5,
    sex: 'm',
    color: 'Tan and White',
    weight: 80,
    parentId: 1,
  },
  {
    id: 22,
    name: 'Jackson',
    breed: 'Lab/Border collie',
    age: 12,
    sex: 'm',
    color: 'Black/white',
    weight: 100,
    parentId: 15,
  },
  {
    id: 23,
    name: 'Lovee',
    breed: 'Bearded Dragon',
    age: 3,
    sex: '?',
    color: 'orange',
    weight: 0.75,
    parentId: 15,
  },
];

const parents = [
  { id: 1, name: 'Sean', password: 'Pa$$word01!!' },
  { id: 2, name: 'Chloe', password: 'Pa$$word01!!' },
  { id: 3, name: 'Christian', password: 'Pa$$word01!!' },
  { id: 4, name: 'Josh', password: 'Pa$$word01!!' },
  { id: 5, name: 'Hayden', password: 'Pa$$word01!!' },
  { id: 6, name: 'Anna', password: 'Pa$$word01!!' },
  { id: 7, name: 'Courtney', password: 'Pa$$word01!!' },
  { id: 8, name: 'Grant', password: 'Pa$$word01!!' },
  { id: 9, name: 'Aparna', password: 'Pa$$word01!!' },
  { id: 10, name: 'Maisha', password: 'Pa$$word01!!' },
  { id: 11, name: 'Natalia', password: 'Pa$$word01!!' },
  { id: 12, name: 'Jason', password: 'Pa$$word01!!' },
  { id: 13, name: 'Evan', password: 'Pa$$word01!!' },
  { id: 14, name: 'Brooke', password: 'Pa$$word01!!' },
  { id: 15, name: 'Peter', password: 'Pa$$word01!!' },
  { id: 16, name: 'Dustin', password: 'Pa$$word01!!' },
];

const tricks = [
  { id: 1, title: 'Be Cute' },
  { id: 2, title: 'Sit' },
  { id: 3, title: 'Shake' },
  { id: 4, title: 'Fetch' },
  { id: 5, title: 'Give a kiss' },
  { id: 6, title: 'Bang! Play dead!' },
  { id: 7, title: 'Lay' },
  { id: 8, title: 'Being a fat chunky doggo' },
  { id: 9, title: 'Scream when hungry' },
  { id: 10, title: 'Stretch' },
  { id: 11, title: 'Climb trees' },
  { id: 12, title: 'Bother their sibling' },
  { id: 13, title: 'sun bathing' },
  { id: 14, title: 'High five' },
  { id: 15, title: 'Guarding' },
  { id: 16, title: 'Balance treat on nose and wait' },
  { id: 17, title: 'Look pretty' },
  { id: 18, title: 'Hug' },
  { id: 19, title: 'Dance' },
  { id: 20, title: 'sleep' },
  { id: 21, title: "Eat mom's favorite fuzzy socks!" },
  { id: 22, title: 'Lick peanut butter off nose. :)' },
];

module.exports = { pets, parents, tricks };

const makeNum = (arr) => {
  arr.forEach((pet) => {
    pet.id = Number(pet.id);
    pet.age = Number(pet.age);
    pet.weight = Number(pet.weight);
    pet.parentId = Number(pet.parentId);
    pet.sex = pet.sex.toLowerCase();
  });
  console.log(arr);
};
const makeNumAgain = (arr) => {
  arr.forEach((parent) => {
    parent.id = Number(parent.id);
  });
  console.log(arr);
};

// makeNumAgain(tricks);
